### ISSUE TITLE
Error starting service

### ISSUE THREAD

**Issue by GGPay** [Snawoot/windscribe-proxy#1]
Got an error.

Was trying a few different command parameters but without any luck . 

Log server below

![image](https://user-images.githubusercontent.com/17413180/125825471-af2b1466-2d41-46a3-8294-d4da42a8a239.png)

**Comment by Snawoot** [comment]
Hi! This message appears after few device registrations in a row, Windscribe bans your IP. However, you can obtain wndstate.json file on some other machine and just reuse it on yours.

**Comment by GGPay** [comment]
@Snawoot  Really appreciate it. Thank you for your help and awesome tools!!!

**Comment by nyuszika7h** [comment]
Is it possible to use another proxy to make the request to Windscribe? It seems like the `http_proxy` and `https_proxy` environment variables are not respected.

**Comment by Snawoot** [comment]
@nyuszika7h Yes, see `-proxy` option.
