### ISSUE TITLE
CRITICAL Cold init failed: Session call failed

### ISSUE THREAD

**Issue by Ulka17** [Snawoot/windscribe-proxy#13]
Hey,
when I'm trying to start the exe file on Windows 10 I get this error.

MAIN    : 2022/09/29 14:04:39 main.go:128: INFO     windscribe-proxy client version v1.2.0 is starting...
MAIN    : 2022/09/29 14:04:39 main.go:195: WARNING  Failed to load client state: open wndstate.json: The system cannot find the file specified.. Performing cold init...
MAIN    : 2022/09/29 14:04:39 main.go:198: CRITICAL Cold init failed: Session call failed: Post "https://api.windscribe.com/Session?platform=chrome": read tcp 192.168.0.221:11342->104.20.93.59:443: wsarecv: An existing connection was forcibly closed by the remote host.

Any suggestions to fix it?

Thanks in advance.

**Comment by Snawoot** [comment]
Just tested on Rostelecom and I see same error. Hopefully I'll fix it soon.

**Comment by Ulka17** [comment]
Hi!

Yes, it is rostelecom.

**Comment by Snawoot** [comment]
Released v1.3.0. Now it is able to contact API, but apparently all servers are banned by their IP. Though, it should start working if Windscribe will rotate their proxy servers to new hosts.

**Comment by Ulka17** [comment]
Thank you.

**Comment by Snawoot** [comment]
@Ulka17 Consider alternatives. These two should work:
* https://github.com/Snawoot/opera-proxy
* https://github.com/Snawoot/hola-proxy
