### ISSUE TITLE
Details of Account

### ISSUE THREAD

**Issue by maxcodeir** [Snawoot/windscribe-proxy#15]
Hello, Thank you for your good program, I enjoyed it and  it's very useful.
How can I see the amount of traffic used?
If possible, put a command for the program to show the details of the user account like: traffic used, reset date, plan type...
 
thank you very much

**Comment by Snawoot** [comment]
Hi!

No such feature is plannet at this moment. Also this new feature for account information will require some additional reverse engineering of Windscribe API. If someone is up to do this work - pull request will be welcome.
