### ISSUE TITLE
Installing Pre Built Error

### ISSUE THREAD

**Issue by rosunad** [Snawoot/windscribe-proxy#17]
Maybe it's not an issue but I'm newbie at Ubuntu. I get this when I execute the prebuilt:

MAIN    : 2022/11/19 01:16:55 main.go:130: INFO     windscribe-proxy client version v1.3.0 is starting...
MAIN    : 2022/11/19 01:16:55 main.go:197: WARNING  Failed to load client state: open wndstate.json: no such file or directory. Performing cold init...
MAIN    : 2022/11/19 01:16:56 main.go:200: CRITICAL Cold init failed: Session call failed: bad http status: 400 Bad Request, headers: http.Header{"Access-Control-Allow-Headers":[]string{"Origin, X-Requested-With, Content-Type, Accept"}, "Access-Control-Allow-Origin":[]string{"*"}, "Cache-Control":[]string{"no-cache, no-store, max-age=0, must-revalidate"}, "Cf-Cache-Status":[]string{"DYNAMIC"}, "Cf-Railgun":[]string{"b4be6faa50 99.99 0.002847 0032 57da"}, "Cf-Ray":[]string{"76c51a75389603ee-LIS"}, "Connection":[]string{"keep-alive"}, "Content-Type":[]string{"text/html; charset=UTF-8"}, "Date":[]string{"Sat, 19 Nov 2022 01:16:56 GMT"}, "Server":[]string{"cloudflare"}, "Strict-Transport-Security":[]string{"max-age=16000000; includeSubDomains; preload;"}}, body: "{\n    \"errorCode\": 502,\n    \"errorMessage\": \"2 arguments had validation errors\",\n    \"errorDescription\": \"Argument did not validate\",\n    \"logStatus\": null,\n    \"validationFailuresArray\": {\n        \"0\": {\n            \"password\": {\n                \"lengthMin\": {\n                    \"argValue\": \"\",\n                    \"validationValue\": \"4\"\n                }\n            }\n        },\n        \"1\": {\n            \"username\": {\n                \"lengthMin\": {\n                    \"argValue\": \"\",\n                    \"validationValue\": \"3\"\n                }\n            }\n        },\n        \"validationErrorMessageArray\": [\n            \"password is too short. Minimum value is 4 characters\",\n            \"username is too short. Minimum value is 3 characters\"\n        ]\n    }\n}"

**Comment by Snawoot** [comment]
Hi! Nowadays they require Windscribe account, which login and password has to be specified with respective options.
