### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by giuseppedima** [Snawoot/windscribe-proxy#18]
Hi,
I was able to start this client flawlessly on my windows 11 pc using prebuilt binaries.
When I tried to use it on linux (debian 11, amd64) pc using prebuild binaries I got this error
`MAIN    : 2022/12/03 00:32:17 main.go:130: INFO     windscribe-proxy client version v1.3.0 is starting...
MAIN    : 2022/12/03 00:32:17 main.go:197: WARNING  Failed to load client state: open wndstate.json: no such file or directory. Performing cold init...
MAIN    : 2022/12/03 00:32:17 main.go:200: CRITICAL Cold init failed: Session call failed: bad http status: 403 Forbidden, headers: http.Header{"Cache-Control":[]string{"private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0"}, "Cf-Ray":[]string{"7737dc66c9347270-HAM"}, "Connection":[]string{"keep-alive"}, "Content-Type":[]string{"text/html; charset=UTF-8"}, "Date":[]string{"Fri, 02 Dec 2022 23:32:17 GMT"}, "Expires":[]string{"Thu, 01 Jan 1970 00:00:01 GMT"}, "Referrer-Policy":[]string{"same-origin"}, "Server":[]string{"cloudflare"}, "Vary":[]string{"Accept-Encoding"}, "X-Frame-Options":[]string{"SAMEORIGIN"}}, body: "<!DOCTYPE html>\n<html lang=\"en-US\">\n<head>\n<title>Access denied</title>\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" href=\"/cdn-cgi/styles/errors.css\" media=\"screen\" />\n<script>\n(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById(\"error-feedback-survey\"),d=document.getElementById(\"error-feedback-success\"),b=new XMLHttpRequest;a={event:\"feedback clicked\",properties:{errorCode:1020,helpful:a,version:4}};b.open(\"POST\",\"https://sparrow.cloudflare.com/api/v1/event\");b.setRequestHeader(\"Content-Type\",\"application/json\");b.setRequestHeader(\"Sparrow-Source-Key\",\"c771f0e4b54944bebf4261d44bd79a1e\");\nb.send(JSON.stringify(a));c.classList.add(\"feedback-hidden\");d.classList.remove(\"feedback-hidden\")};document.addEventListener(\"DOMContentLoaded\",function(){var a=document.getElementById(\"er"
giuseppe@vmi1050322:~$ /websites/tools/windscribe-proxy.linux-amd64 -username=giuseppe -password=Valentino123
MAIN    : 2022/12/03 00:33:15 main.go:130: INFO     windscribe-proxy client version v1.3.0 is starting...
MAIN    : 2022/12/03 00:33:15 main.go:197: WARNING  Failed to load client state: open wndstate.json: no such file or directory. Performing cold init...
MAIN    : 2022/12/03 00:33:15 main.go:200: CRITICAL Cold init failed: Session call failed: bad http status: 403 Forbidden, headers: http.Header{"Cache-Control":[]string{"private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0"}, "Cf-Ray":[]string{"7737ddd19fbeca79-HAM"}, "Connection":[]string{"keep-alive"}, "Content-Type":[]string{"text/html; charset=UTF-8"}, "Date":[]string{"Fri, 02 Dec 2022 23:33:15 GMT"}, "Expires":[]string{"Thu, 01 Jan 1970 00:00:01 GMT"}, "Referrer-Policy":[]string{"same-origin"}, "Server":[]string{"cloudflare"}, "Vary":[]string{"Accept-Encoding"}, "X-Frame-Options":[]string{"SAMEORIGIN"}}, body: "<!DOCTYPE html>\n<html lang=\"en-US\">\n<head>\n<title>Access denied</title>\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" href=\"/cdn-cgi/styles/errors.css\" media=\"screen\" />\n<script>\n(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById(\"error-feedback-survey\"),d=document.getElementById(\"error-feedback-success\"),b=new XMLHttpRequest;a={event:\"feedback clicked\",properties:{errorCode:1020,helpful:a,version:4}};b.open(\"POST\",\"https://sparrow.cloudflare.com/api/v1/event\");b.setRequestHeader(\"Content-Type\",\"application/json\");b.setRequestHeader(\"Sparrow-Source-Key\",\"c771f0e4b54944bebf4261d44bd79a1e\");\nb.send(JSON.stringify(a));c.classList.add(\"feedback-hidden\");d.classList.remove(\"feedback-hidden\")};document.addEventListener(\"DOMContentLoaded\",function(){var a=document.getElementById(\"er"
giuseppe@vmi1050322:~$ /websites/tools/windscribe-proxy.linux-amd64 -username=giuseppe -password=Valentino123
MAIN    : 2022/12/03 00:34:16 main.go:130: INFO     windscribe-proxy client version v1.3.0 is starting...
MAIN    : 2022/12/03 00:34:16 main.go:197: WARNING  Failed to load client state: open wndstate.json: no such file or directory. Performing cold init...
MAIN    : 2022/12/03 00:34:16 main.go:200: CRITICAL Cold init failed: Session call failed: bad http status: 403 Forbidden, headers: http.Header{"Cache-Control":[]string{"private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0"}, "Cf-Ray":[]string{"7737df4eeea4bb53-FRA"}, "Connection":[]string{"keep-alive"}, "Content-Type":[]string{"text/html; charset=UTF-8"}, "Date":[]string{"Fri, 02 Dec 2022 23:34:16 GMT"}, "Expires":[]string{"Thu, 01 Jan 1970 00:00:01 GMT"}, "Referrer-Policy":[]string{"same-origin"}, "Server":[]string{"cloudflare"}, "Vary":[]string{"Accept-Encoding"}, "X-Frame-Options":[]string{"SAMEORIGIN"}}, body: "<!DOCTYPE html>\n<html lang=\"en-US\">\n<head>\n<title>Access denied</title>\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" href=\"/cdn-cgi/styles/errors.css\" media=\"screen\" />\n<script>\n(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById(\"error-feedback-survey\"),d=document.getElementById(\"error-feedback-success\"),b=new XMLHttpRequest;a={event:\"feedback clicked\",properties:{errorCode:1020,helpful:a,version:4}};b.open(\"POST\",\"https://sparrow.cloudflare.com/api/v1/event\");b.setRequestHeader(\"Content-Type\",\"application/json\");b.setRequestHeader(\"Sparrow-Source-Key\",\"c771f0e4b54944bebf4261d44bd79a1e\");\nb.send(JSON.stringify(a));c.classList.add(\"feedback-hidden\");d.classList.remove(\"feedback-hidden\")};document.addEventListener(\"DOMContentLoaded\",function(){var a=document.getElementById(\"er"`

I also tried to copy the wndstate.json from my windows pc (as read in another closed issue) and using it, but got the same error:
`MAIN    : 2022/12/03 00:42:34 main.go:130: INFO     windscribe-proxy client version v1.3.0 is starting...
MAIN    : 2022/12/03 00:42:34 main.go:239: CRITICAL Unable to get best location endpoint: bad http status: 403 Forbidden, headers: http.Header{"Cache-Control":[]string{"private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0"}, "Cf-Ray":[]string{"7737eb79cb50ca43-HAM"}, "Connection":[]string{"keep-alive"}, "Content-Type":[]string{"text/html; charset=UTF-8"}, "Date":[]string{"Fri, 02 Dec 2022 23:42:34 GMT"}, "Expires":[]string{"Thu, 01 Jan 1970 00:00:01 GMT"}, "Referrer-Policy":[]string{"same-origin"}, "Server":[]string{"cloudflare"}, "Vary":[]string{"Accept-Encoding"}, "X-Frame-Options":[]string{"SAMEORIGIN"}}, body: "<!DOCTYPE html>\n<html lang=\"en-US\">\n<head>\n<title>Access denied</title>\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" href=\"/cdn-cgi/styles/errors.css\" media=\"screen\" />\n<script>\n(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById(\"error-feedback-survey\"),d=document.getElementById(\"error-feedback-success\"),b=new XMLHttpRequest;a={event:\"feedback clicked\",properties:{errorCode:1020,helpful:a,version:4}};b.open(\"POST\",\"https://sparrow.cloudflare.com/api/v1/event\");b.setRequestHeader(\"Content-Type\",\"application/json\");b.setRequestHeader(\"Sparrow-Source-Key\",\"c771f0e4b54944bebf4261d44bd79a1e\");\nb.send(JSON.stringify(a));c.classList.add(\"feedback-hidden\");d.classList.remove(\"feedback-hidden\")};document.addEventListener(\"DOMContentLoaded\",function(){var a=document.getElementById(\"er"`

**Comment by Snawoot** [comment]
Duplicate with #17. See resolution: https://github.com/Snawoot/windscribe-proxy/issues/17#issuecomment-1320825522

**Comment by giuseppedima** [comment]
Hi again,
Thanks for reply.
I think you misread my question because:
- I started the program using username and password, I already read that issue before opening another one. (The command I am using is `/path/windscribe-proxy.linux-amd64 -username myusername -password mypassword`)
- As stated in the question I tried also to use a wndstate.json generated on my windows pc, on which the program worked flawlessly
- My error is 403 Forbidden and not 400 Bad Request as in that issue

**Comment by giuseppedima** [comment]
@Snawoot

**Comment by Snawoot** [comment]
hi, @giuseppedima 

maybe you're using this proxy from datacenter IP address?

**Comment by giuseppedima** [comment]
> hi, @giuseppedima
> 
> maybe you're using this proxy from datacenter IP address?

Yes, I am using a vps.
I read this [answer](https://github.com/Snawoot/windscribe-proxy/issues/8#issuecomment-1172900098) on issue #8 and thought that using a wndstate.json generated on my pc would work, but it doesn't.
If there is no other solution I'll switch to [opera-proxy](https://github.com/Snawoot/opera-proxy) or [hola-proxy](https://github.com/Snawoot/hola-proxy) (I already tried them and they work on the vps, but I preferred windscribe because of the variety of choice for locations). 
Thanks for your time 🙏

**Comment by Snawoot** [comment]
Hi! It seems there is not much I can do about it: likely Windscribe restricts access from datacenter IP addresses and I have no influence on that. Probably it is possible to export proxy credentials from windscribe-proxy, running on your PC and use them on VPS. See output of `windscribe-proxy -list-proxies`. Tho, using them directly is a bit challenging: you have to connect to proxy using IP address, validate certs using given domain name and provide `Proxy-Authorization` header in all proxy requests.
