### ISSUE TITLE
can't use locations with space?

### ISSUE THREAD

**Issue by gnafrgb** [Snawoot/windscribe-proxy#20]
sorry maybe it's a silly question.

I can use this program in win10. It works quite well. 
but I can only use locations like Japan/Tokyo, Australia/Sydney... those names without space.
if I try -location US West/Los Angeles
it always return CRITICAL Server for location "US" not found.
I tried to remove the space like USWest/LosAngeles, but it still didn't work.
how do I use those location name with space?

**Comment by Snawoot** [comment]
Hi!

Try to add double quotes around location name.

E.g.: ` windscribe-proxy.windows-amd64.exe -location "US East/Chicago"`
