### ISSUE TITLE
Verbosity not respected

### ISSUE THREAD

**Issue by androidacy-user** [Snawoot/windscribe-proxy#22]
I.e., `-verbosity 30` is still showing INFO level

**Comment by Snawoot** [comment]
Hello!

INFO messages will be shown on INFO verbosity level or greater. If verbosity level is greater than INFO, INFO messages will not be shown. That's normal.

**Comment by Snawoot** [comment]
```
user@hp:~> windscribe-proxy -bind-address 0.0.0.0:80
MAIN    : 2023/03/18 14:49:45 main.go:130: INFO     windscribe-proxy client version v1.3.0 is starting...
MAIN    : 2023/03/18 14:49:45 main.go:257: INFO     Endpoint: ro-014.whiskergalaxy.com:443
MAIN    : 2023/03/18 14:49:45 main.go:258: INFO     Starting proxy server...
MAIN    : 2023/03/18 14:49:45 main.go:260: INFO     Init complete.
MAIN    : 2023/03/18 14:49:45 main.go:262: CRITICAL Server terminated with a reason: listen tcp 0.0.0.0:80: bind: permission denied
MAIN    : 2023/03/18 14:49:45 main.go:263: INFO     Shutting down...
user@hp:~> windscribe-proxy -bind-address 0.0.0.0:80 -verbosity 30
MAIN    : 2023/03/18 14:49:53 main.go:262: CRITICAL Server terminated with a reason: listen tcp 0.0.0.0:80: bind: permission denied
```

It works as expected. Maybe I'm missing something?

**Comment by Snawoot** [comment]
> > ```
> > user@hp:~> windscribe-proxy -bind-address 0.0.0.0:80
> > MAIN    : 2023/03/18 14:49:45 main.go:130: INFO     windscribe-proxy client version v1.3.0 is starting...
> > MAIN    : 2023/03/18 14:49:45 main.go:257: INFO     Endpoint: ro-014.whiskergalaxy.com:443
> > MAIN    : 2023/03/18 14:49:45 main.go:258: INFO     Starting proxy server...
> > MAIN    : 2023/03/18 14:49:45 main.go:260: INFO     Init complete.
> > MAIN    : 2023/03/18 14:49:45 main.go:262: CRITICAL Server terminated with a reason: listen tcp 0.0.0.0:80: bind: permission denied
> > MAIN    : 2023/03/18 14:49:45 main.go:263: INFO     Shutting down...
> > user@hp:~> windscribe-proxy -bind-address 0.0.0.0:80 -verbosity 30
> > MAIN    : 2023/03/18 14:49:53 main.go:262: CRITICAL Server terminated with a reason: listen tcp 0.0.0.0:80: bind: permission denied
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It works as expected. Maybe I'm missing something?
> 
> I'm talking about the verbosity param that's supposed to turn down logging, which you didn't even pass. I.e. I don't want all those proxy connection lines, which are INFO level

See the bottom of the output. It shows second launch with verbosity param, leaving only WARN and greater severity level.
