### ISSUE TITLE
wndstate.json missing. http 400  and i guess wron auth secret.

### ISSUE THREAD

**Issue by cdprf** [Snawoot/windscribe-proxy#23]
i guess you can easly understand the problem by checking this logs. how can solve ?

.\windscribe-proxy.exe --list-locations
MAIN    : 2023/05/24 06:42:38 main.go:130: INFO     windscribe-proxy client version v1.3.0 is starting...
MAIN    : 2023/05/24 06:42:38 main.go:197: WARNING  Failed to load client state: open wndstate.json: The system cannot find the file specified.. Performing cold init...
MAIN    : 2023/05/24 06:42:43 main.go:200: CRITICAL Cold init failed: Session call failed: bad http status: 400 Bad Request, headers: http.Header{"Access-Control-Allow-Headers":[]string{"Origin, X-Requested-With, Content-Type, Accept"}, "Access-Control-Allow-Origin":[]string{"*"}, "Cache-Control":[]string{"no-cache, no-store, max-age=0, must-revalidate"}, "Cf-Cache-Status":[]string{"DYNAMIC"}, "Cf-Ray":[]string{"7cc287653b5b5075-IST"}, "Connection":[]string{"keep-alive"}, "Content-Type":[]string{"text/html; charset=UTF-8"}, "Date":[]string{"Wed, 24 May 2023 03:42:28 GMT"}, "Server":[]string{"cloudflare"}, "Strict-Transport-Security":[]string{"max-age=16000000; includeSubDomains; preload;"}}, body: "{\n    \"errorCode\": 502,\n    \"errorMessage\": \"2 arguments had validation errors\",\n    \"errorDescription\": \"Argument did not validate\",\n    \"logStatus\": null,\n    \"validationFailuresArray\": {\n        \"0\": {\n            \"password\": {\n                \"lengthMin\": {\n                    \"argValue\": \"\",\n                    \"validationValue\": \"4\"\n                }\n            }\n        },\n        \"1\": {\n            \"username\": {\n                \"lengthMin\": {\n                    \"argValue\": \"\",\n                    \"validationValue\": \"3\"\n                }\n            }\n        },\n        \"validationErrorMessageArray\": [\n            \"password is too short. Minimum value is 4 characters\",\n            \"username is too short. Minimum value is 3 characters\"\n        ]\n    }\n}"

**Comment by cdprf** [comment]
thanks i am allready using both of them, i just want to expand my archive. and now its ok. thnaks.

**Comment by PalasX** [comment]
-username and -password work in windows command line binary, but not in latest docker image. i tried passing as environment entries in docker-compose.yml, as well as arguments in command: in docker-compose.yml
cold init fails with 
INFO     windscribe-proxy client version v1.3.0 is starting...
WARNING  Failed to load client state: open /state/wndstate.json: no such file or directory. Performing cold init...
CRITICAL Cold init failed: Session call failed: bad http status: 403 Forbidden, headers: http.Header{"Cache-Control":[]string{"no-cache"}, "Cf-Cache-Status":[]string{"DYNAMIC"}, "Cf-Ray":[]string{"7e66b2bd0f6d0a15-IAD"}, "Connection":[]string{"keep-alive"}, "Content-Type":[]string{"text/html"}, "Date":[]string{"Fri, 14 Jul 2023 03:32:23 GMT"}, "Server":[]string{"cloudflare"}}, body: "<html><body>\n</body></html>

suggestions for using login info with docker container?
