### ISSUE TITLE
Can i use my own windscribe.com account so I don't get my ip banned 

### ISSUE THREAD

**Issue by beshoo** [Snawoot/windscribe-proxy#3]
Please advise how to setup the wndstate.json and how to fill my information in that file
Regards

**Comment by Vangelis66** [comment]
... This should be now possible using any version of `windscribe-proxy >=1.1.0`; just delete(/remove/backup) existing version of the `wndstate.json` file and then perform a "cold init" via supplying your **Windscribe account's log-in credentials**: 
```
windscribe-proxy -username (your WS account UN) -password (your WS account PW)
```
Hopefully, the app will successfully log-in to your existing WS account and then a valid/working new `wndstate.json` file will be created; next time, you'll have to launch the app in the normal fashion, without providing credentials (unless you signed yourself out via the dedicated Windscribe account management page, 
https://windscribe.com/myaccount, ?) ...
