### ISSUE TITLE
Windscribe sends tons of "security alert" emails and blocks the account after ~70 of them

### ISSUE THREAD

**Issue by kvtb** [Snawoot/windscribe-proxy#30]
Windscribe sends tons of "security alert" emails and blocka account after ~70 of them:

> Your account is exhibiting suspicious activity, namely, you have an unusually high amount of successful logins into your account. This can happen if you re-used an insecure password that you used on other websites that may have been compromised in the past. You can check for this here. Alternatively, this can happen if you shared your account with all your friends which is against our Terms of Service.

`windscribe-proxy` could try to save and reuse previous login between runs to mitigate the problem.
Currently, running say 10 proxies implies 10 login attempts

**Comment by Snawoot** [comment]
hi!

It doesn't do login on each command. It stores and reuses session data in `wndstate.json` whenever this file is available UNLESS special option `-force-cold-init` is passed via command line. Maybe you're running it in docker and it discards state of writable layer / hasn't persistent volume mounted?

**Comment by kvtb** [comment]
I'll check, than you for the hint!
