### ISSUE TITLE
Location selection issue

### ISSUE THREAD

**Issue by Badawika** [Snawoot/windscribe-proxy#31]
Dear Snawoot,

First of all, I want to thank you a million for this application as I have used it to grab my windscribe proxy credentials to use them in other tunneling applications, i.e. Adguard, besides the normal running of the application. However, I am facing a problem with the location selection feature. I can not specify the accurate server to initiate a connection, for example, South Korea has 4 servers and the application just selects the endpoints on its preference. When I put the "location, server-URL, 443" it replies with "Server location error".

So, how can I manually select the server of my preference manually from a specific listed location correctly without getting this error?

Many thanks and waiting for your reply.

**Comment by Snawoot** [comment]
Hi!

Such feature for manual server selection is not implemented and not planned. However, you can try following workaround:

1. Get list of proxies from windscribe with `windscribe-proxy -list-proxies` command.
2. Run dumbproxy in upstream proxy forwarding mode: `dumbproxy -proxy 'https://PROXY_LOGIN:PROXY_PASSWORD@SERVER_NAME:443'`

where `PROXY_LOGIN` and `PROXY_PASSWORD` is respective credentials which can be found in the beginning of output of `windscribe-proxy -list-proxies` (not your windscribe login and password!). dumbproxy will be running on port 8080 and can be used same as windscribe-proxy.

**Comment by Badawika** [comment]
Hi, 

I tried your solution and it works, thanks.

I was before using a similar way by using the "-Proxy" switch and adding manual configs of my preferred server to enforce windscribe-proxy to connect to this server location. I wonder if I use this way, does it mean that it is double tunneled and data will be transferred through two proxies (a small proxy chain), or the 1st proxy is used only for DNS resolving and handshaking processes?

Thanks in advance.

**Comment by Snawoot** [comment]
> I wonder if I use this way, does it mean that it is double tunneled and data will be transferred through two proxies (a small proxy chain), or the 1st proxy is used only for DNS resolving and handshaking processes?

It will be a chain.
