### ISSUE TITLE
Please consider adding other protocols in addition to the TCP

### ISSUE THREAD

**Issue by ioctl-user** [Snawoot/windscribe-proxy#33]
Here is my docker run log:

```
...
MAIN    : *** *** main.go:207: CRITICAL Cold init failed: Session call failed: Post "https://api.windscribe.com/Session?platform=chrome": read tcp ***:***->104.20.89.86:443: read: connection reset by peer
```

I'm running docker from the network, where api.windscribe.com is not accessible via TCP. Mobile app has the same problems, however, it can connect via UDP to the port 443.

Could you, please, add a manual option or autoselect feature to chose other protocols in addition to the TCP?

**Comment by Snawoot** [comment]
Hello!

Not sure what you're talking about. It's not a tunnel request, it's a request to API to create session, which happens over HTTPS. HTTPS can work via UDP only if HTTP/3 and QUIC is enabled on server, but it doesn't seem to be the case with api.windscribe.com, so for that request there is no alternative to TCP transport for that particular request.

It is possible windscribe apps use some alternative domains to interact with API, but I don't know anything about such mechanism and logic behind it.

**Comment by ioctl-user** [comment]
Seems, mobile app uses some other method.

If you don't aware of it, issue is over.
