### ISSUE TITLE
go version

### ISSUE THREAD

**Issue by THMaST3R** [Snawoot/windscribe-proxy#37]
Hi!
Which version of go do you need?
I tried on version 1.21.1 but it didn't work

**Comment by Snawoot** [comment]
Hi!

What error do you get?

**Comment by THMaST3R** [comment]
I fixed it thankyou 
but still i have one problem
i have 3 upgraded loc but it dosent showing my locations

**Comment by Snawoot** [comment]
> I fixed it thankyou but still i have one problem i have 3 upgraded loc but it dosent showing my locations

Probably something is not right with the acquisition of locations list. I don't know what exactly :man_shrugging: If you feel it is important, file a separate issue or maybe even look into windscribe extension code to port their API and send a pull request.
