### ISSUE TITLE
Bugs Report

### ISSUE THREAD

**Issue by THMaST3R** [Snawoot/windscribe-proxy#38]
Hi!
There are some bugs with this script. It doesn't open certain websites, even though the same websites open with an extension or program.

I tried diffrent locations

Another bug that exists is with locations that have spaces between them, like 'United Kingdom/London.' Even though they are in the list of locations, not founded.

![image](https://github.com/user-attachments/assets/d4dd9992-73c2-4ee8-b12b-0daffe7173e8)

**Comment by Snawoot** [comment]
Hi!

> There are some bugs with this script.

It's not a script, it's an application.

> It doesn't open certain websites, even though the same websites open with an extension or program.

Which ones, for example?

> Another bug that exists is with locations that have spaces between them, like 'United Kingdom/London.' Even though they are in the list of locations, not founded.

It's not an app bug. In order to pass shell parameter which contains space, you have to put that parameter in quotes. E.g. `-location "United Kingdom/London"`
That's common rules for all CLI stuff.

**Comment by THMaST3R** [comment]
> Hi!
> 
> > There are some bugs with this script.
> 
> It's not a script, it's an application.
> 
> > It doesn't open certain websites, even though the same websites open with an extension or program.
> 
> Which ones, for example?
> 
> > Another bug that exists is with locations that have spaces between them, like 'United Kingdom/London.' Even though they are in the list of locations, not founded.
> 
> It's not an app bug. In order to pass shell parameter which contains space, you have to put that parameter in quotes. E.g. `-location "United Kingdom/London"` That's common rules for all CLI stuff.

oh my bad

for example microsoft 
whatsapp
sometimes speedtest.net

**Comment by Snawoot** [comment]
> microsoft
> whatsapp
> sometimes speedtest.net

Which error do you get on these sites? Could you share a screenshot?

**Comment by THMaST3R** [comment]
nothing just
![image](https://github.com/user-attachments/assets/b9c9b6dc-924b-4439-a5c5-ac696ee072b1)
This is the case when it loads easily with its app and extension on Windows and Chrome at same location

**Comment by THMaST3R** [comment]
Is this bug fixed or not?

**Comment by Snawoot** [comment]
> Is this bug fixed or not?

I checked, these sites you mentioned opened through windscribe-proxy just fine for me. Can't reproduce the issue.
