### ISSUE TITLE
Available for mac?

### ISSUE THREAD

**Issue by Katerou22** [Snawoot/windscribe-proxy#5]
How i can use this on mac? i did make install but command not found windscribe-proxy

I tried install it on ubuntu server, same problem.

**Comment by Snawoot** [comment]
Hello,

Installed binary should be in `~/go/bin/windscribe-proxy` (where `~` denotes home directory).

Alternative option is to use binary downloaded from releases page (MacOS binaries are ones with `darwin` in their names).
